extend material graph-api
google/model-viewer pull request #1979
Opened 2021-01-27 14:20 UTC by matios13

with alphaMode , doubleSded and cutoff. 

Based on threejs implementation and [ModelViewerGLTFInstance](model-viewer/packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts )

### Reference Issue

2021-01-27 14:21 UTC, matios13 commented
@googlebot I signed it!

2021-01-28 23:49 UTC, elalish requested changes
Thanks for taking the initiative here! Would you mind adding a few tests?

2021-01-28 23:49 UTC, elalish commented on packages/model-viewer/src/features/scene-graph/material.ts
> +      // with the glTF spec.
👍

2021-01-28 23:49 UTC, elalish commented on packages/model-viewer/src/features/scene-graph/material.ts
> +  setDoubleSided(doubleSided: boolean) {
The trouble here is that we do some special stuff for materials that are transparent and double-sided in order to get the triangle sorting working mostly right: https://github.com/google/model-viewer/blob/b5b86b3f681dc724fe9499c192041d2aa4e19fd8/packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts#L77-L113

The trouble is that the special stuff is changes to the mesh objects that use this material, so I think you'll have to do a quick traversal to find meshes you may need to modify.

2021-01-28 23:49 UTC, elalish commented on packages/model-viewer/src/features/scene-graph/material.ts
> +        material.alphaTest = value;
It might be nice to make functions of things like this so that we can reduce duplication between here and `ModelViewerGLTFInstance.ts`.

2021-07-28 22:56 UTC, elalish commented
Thanks! Closing if favor #2616

2021-07-28 22:56 UTC, closed without merging