Pan keys 1
google/model-viewer pull request #3703
Opened 2022-08-10 22:54 UTC by clochardM33

### Reference Issue
Relates primarily to discussion #3484 and subsiquently #3517 and #3519 

This is an PR to add panning to the keyboard controls.
If enablePan is true and the Shift key is down the arrow keys implement panning rather than orbiting.
The step size is set by a constant in SmoothControls.ts

2022-08-10 23:12 UTC, elalish requested changes
Looking good! Thanks for splitting things up. Also, did you run clang-format on this? We have a .clang-format file that should help keep the style consistent.

2022-08-10 23:12 UTC, elalish commented on packages/model-viewer/src/three-components/SmoothControls.ts
> +    // releventKey as the return value is to get the condition back to the calling function as don't have pass by reference arguments in js
Actually, all arguments in js are passed by reference (except literals like number). How about you move the `event.preventDefault();` into these functions and avoid the return?

2022-08-10 23:12 UTC, elalish commented on packages/model-viewer/src/three-components/SmoothControls.ts
> +      case 'PageDown':
I'd been meaning to update these for ages; thank you!

2022-08-10 23:12 UTC, elalish commented on packages/model-viewer/src/three-components/SmoothControls.ts
> +    // else == ORBIT/ZOOM
Honestly, this logic is equally clear from reading the code, so I think we can skip this comment. Self-documenting code is ideal!

2022-08-10 23:19 UTC, clochardM33 commented
Ooh no I forgot clang. It's on a different pc and it's a ground up wsl and vs code install.
Will try ASAP. Any other that I can catch at the same time?

2022-08-10 23:23 UTC, elalish commented
That and the other two requested changes should be enough to merge this.

2022-08-10 23:33 UTC, elalish commented
Also, the tests are failing; did you run `npm test` locally? Should be an easy fix.

2022-08-11 00:06 UTC, clochardM33 commented
Nope, will do.

On Wed, 10 Aug 2022, 19:33 Emmett Lalish, ***@***.***> wrote:

> Also, the tests are failing; did you run npm test locally? Should be an
> easy fix.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google/model-viewer/pull/3703#issuecomment-1211402975>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVABBVUGAP2A6R2LRYG6743VYQ33XANCNFSM56GGZHDQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-11 01:55 UTC, clochardM33 commented
> Also, the tests are failing; did you run `npm test` locally? Should be an easy fix.

Easier to say that to fix!
Help required. The fails all occur with lines such as this...
`dispatchSyntheticEvent(element, 'keydown', { keyCode: KeyCode.UP });`
Presumably the fail relates to the keyhandler no longer looking for `KeyCode.XYZ` and is going after `event.key`
If so what would be the change of syntax in the custom parameters?

2022-08-11 20:23 UTC, elalish commented
Agreed; I think you just need to update the tests accordingly to set `key` instead of `KeyCode`. You might also want to add some similar tests for pan.

2022-08-15 18:15 UTC, elalish commented
To be more specific: `dispatchSyntheticEvent(element, 'keydown', { keyCode: KeyCode.UP });` becomes `dispatchSyntheticEvent(element, 'keydown', { key: 'ArrowUp' });`, but to fix TS, you also need to change [this line](https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/test/helpers.ts#L55) to `key?: string`.

2022-08-15 18:24 UTC, clochardM33 commented
Great. I'll get on it. Still suffering from holiday / WiFi / time this
week.
Thanks.

On Mon, 15 Aug 2022, 19:15 Emmett Lalish, ***@***.***> wrote:

> To be more specific: dispatchSyntheticEvent(element, 'keydown', {
> keyCode: KeyCode.UP }); becomes dispatchSyntheticEvent(element,
> 'keydown', { key: 'ArrowUp' });, but to fix TS, you also need to change this
> line
> <https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/test/helpers.ts#L55>
> to key?: string.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google/model-viewer/pull/3703#issuecomment-1215556706>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVABBVVXMFAXP3LMQ2OH7ZTVZKCN7ANCNFSM56GGZHDQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-17 14:19 UTC, clochardM33 commented
Today's question.
Key events and helper.ts updated, but how do I get past the two cases of:
`import {ChangeSource, KeyCode, SmoothControls} from '../../three-components/SmoothControls.js';`
without putting a placeholder reference to a KeyCode somewhere?
If the line is commented out the error panel lights up with missing Smooth Controls references.
If it is left in with some null tests to make a reference to a KeyCode then it ends up with 6 skipped tests rather than 6 failed tests (which is some kind of progress).
P.S. Working from a carpark is not conducive to creative thinking so I'm all up for being spoon fed.
Thanks.

2022-08-17 16:18 UTC, elalish commented
You should be able to update *all* usages of `KeyCode` to `key` and then you won't need to import it at all. If you're still having trouble, just push your latest and I'll take a look.

2022-08-17 21:38 UTC, clochardM33 commented
Progress. The snag was that I didn't spot that the arguments in `import {ChangeSource, ...` was just a list of arguments.
Next question. How do you pass a the shift key in to the keydown event so that the pan function can be tested?
I have dropped a place holder test in, but it is currently just a copy of the orbit test.
Next commit coming up asap.
Thanks.

2022-08-17 21:40 UTC, clochardM33 reviewed
Revision of test to swap KeyCode to key and all the related tidyups.
But how do you pass a modifier key (ie Shift) into the keydown event?

2022-08-17 21:48 UTC, elalish commented
From [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent) it looks like `{ key: 'ArrowUp', shiftKey: true }` should do the trick.

2022-08-17 21:49 UTC, elalish commented
And remember to pull master and fix the conflicts :)

2022-08-18 21:47 UTC, clochardM33 commented
> And remember to pull master and fix the conflicts :)

This is just another thing on the don't-know-how-to-do-that list. 
Typed git pull origin master after updating my master branch on fork and all hell broke loose.



> From [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent) it looks like `{ key: 'ArrowUp', shiftKey: true }` should do the trick.

Perfect. That is in, but I can't make any sense of the expect condtion. Pls see commit.

2022-08-18 21:51 UTC, clochardM33 reviewed
Added Pan key test, but can't make sense of the expect logic.
Using logging the numeric values are the same as the logic conditions, but the test fails saying the numbers are not different, but they are! Please sprinkle magic understanding powder on it.

2022-08-18 23:01 UTC, elalish approved these changes
Okay, there were some tricky merge conflicts, so I went ahead and took care those (they were my fault anyway). You test was failing because it had in fact unearthed an existing bug in `getTarget()`, so that's now fixed too. No problems in your code. Thanks for sticking with this!

2022-08-18 23:12 UTC, merged

2022-08-20 07:54 UTC, clochardM33 commented
Thank you so much for finishing this off. The last hurdle was way out of my league.
My initial plan was to have a test for each individual key. If needed I can add them, if not then job done.

2022-08-22 17:22 UTC, elalish commented
Thanks! Always welcome, but honestly beyond our current level of testing 😄