enable complex line arguments for update-renderer command
google/model-viewer pull request #4542
Opened 2023-10-26 18:38 UTC by bhouston

This implements this idea: https://github.com/google/model-viewer/issues/4536

```
Options:
      --version       Show version number                              [boolean]
  -c, --config        Path to configuration json             [string] [required]
  -r, --renderer      Limit to specific renderers                        [array]
  -s, --scenario      Limit to specific scenarios                        [array]
  -m, --missing-only  Only render if an output image is missing
                                                      [boolean] [default: false]
  -d, --dry-run       Lists which images would be rendered but doesn't render
                                                      [boolean] [default: false]
  -q, --quiet         Hide the puppeteer controlled browser
                                                      [boolean] [default: false]
  -h, --help          Show help                                        [boolean]
```

To run a subset of renders or scenarios do something like this:

```
% npm run update-screenshots -- --renderer=filament --renderer=model-viewer -q 
```

2023-10-26 22:52 UTC, elalish requested changes
This looks great, but can you update our [README](https://github.com/google/model-viewer/tree/master/packages/render-fidelity-tools#render-fidelity-tools) with the descriptions from your comment? I'm going to give you the benefit of the doubt that you've tested this yourself, since you're using it more than I am at the moment anyway.

2023-10-27 00:52 UTC, bhouston commented
@elalish I've updated the README for "npm run update-screenshots" here: https://github.com/google/model-viewer/blob/aa653126a2faa6a4d0073c65f5d7b97da2c1fee2/packages/render-fidelity-tools/README.mdhttps://github.com/google/model-viewer/blob/aa653126a2faa6a4d0073c65f5d7b97da2c1fee2/packages/render-fidelity-tools/README.md

2023-10-27 01:52 UTC, bhouston commented
I've merged in the "npm run test" CLI update into this PR to make it simpler.  I've also further updated the README to contain both sets of options in it.

2023-10-27 12:23 UTC, bhouston commented
I've renamed "npm run update-screenshots" to "npm run render-golden", it is much more accurate/descriptive, e.g. the script renders the images that go into the goldens folder.

2023-10-27 12:38 UTC, bhouston commented
In the latest push I've made it so that the renderer you are testing for fidelity is configurable. It defaults to "model-viewer" (for full backwards compatibility) but you can specify any of the web-based renderers (filament, babylon, gltf-sample-viewer, three-gpu-renderer) and it works.

2023-10-27 16:42 UTC, elalish approved these changes
Thank you, this looks like a huge improvement in usability!

2023-10-27 16:42 UTC, elalish commented on packages/render-fidelity-tools/README.md
> +  -m, --missing-only | false | Only render if an output image is missing.  Very useful when adding new tests.
👍

2023-10-27 19:10 UTC, merged